### ISSUE TITLE
Didn't work on icons that placed on library modules.

### ISSUE THREAD

**Issue by ewgcat** [2BAB/ScratchPaper#3]

**Comment by ewgcat** [comment]
支持么

**Comment by 2BAB** [comment]
@ewgcat Sorry, but what is kotlin.appt3? You mean import the plugin into Kotlin Gradle DSL? (currently I only give a Groovy Gradle DSL example which shows like below)

```
apply plugin: 'me.2bab.scratchpaper'
scratchPaper {
    textSize = 11
    textColor = "#FFFFFFFF"
    verticalLinePadding = 4
    backgroundColor = "#99000000"
    extraInfo = new Date().format("MM-dd,HH:mm")
    enableGenerateIconOverlay = true
    enableGenerateBuildInfo = true
    
    // Experimental field
    // @see IconOverlayGenerator#removeXmlIconFiles
    enableXmlIconRemove = false
}
```

If I get a wrong point, could you please describe it more clearly?

**Comment by ewgcat** [comment]
1

**Comment by ewgcat** [comment]
我按你的配置没有生效

**Comment by ewgcat** [comment]
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        jcenter()
        google()
        maven { url 'https://jitpack.io' }
        flatDir {
            dirs 'libs', '../club_module/libs'
            dirs 'libs', '../commonlib/libs'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2' // add plugin
        classpath "com.tencent.bugly:tinker-support:1.1.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
    }
}

allprojects {
    repositories {
        jcenter()
        google()
        maven { url 'https://jitpack.io' }
        flatDir {
            dirs 'libs', '../club_module/libs'
            dirs 'libs', '../commonlib/libs'
        }
    }
}

ext {
    minSdkVersion = 21
    targetSdkVersion = 25
    compileSdkVersion = 28
    buildToolsVersion = '28.0.3'
    applicationId = "com.yijian.staff"
    versionCode = 40
    versionName = "1.5.0"
    supportLibVersion = "27.1.1"
    designVersion = "27.1.1"
    dbVersion = 7
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
我的项目

**Comment by ewgcat** [comment]
app gradle

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply from: 'tinker-support.gradle'
repositories {
    flatDir {
        dirs 'libs'
    }
}
android {
    dexOptions {
        javaMaxHeapSize "6g"
    }

    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        applicationId rootProject.applicationId
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode rootProject.versionCode
        versionName rootProject.versionName
        flavorDimensions '' + rootProject.versionCode
        resConfigs "zh"
        multiDexEnabled true

        //使用renderscript 兼容包
        renderscriptTargetApi 25
        renderscriptSupportModeEnabled true

        vectorDrawables.useSupportLibrary true
        javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true
        ndk {
            abiFilters "arm64-v8a"
        }

        kapt {
            arguments {
                arg("moduleName", project.getName())
            }
        }
        manifestPlaceholders = [
                JPUSH_PKGNAME: applicationId,
                JPUSH_APPKEY : "$jpush_appkey", //JPush上注册的包名对应的appkey.
                JPUSH_CHANNEL: "developer-default", //暂时填写默认值即可.
        ]
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    signingConfigs {
        releaseKey {
            keyAlias release_key_alias
            keyPassword release_key_password
            storeFile new File(rootProject.projectDir, "releaseKey.jks")
            storePassword release_store_password
        }
    }
    buildTypes {
        debug {
            //混淆
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.releaseKey
        }
        release {
            //混淆
            minifyEnabled true
            shrinkResources true
            zipAlignEnabled true
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.releaseKey
        }
    }
    productFlavors {
        dev {
            buildConfigField "String", "HOST", "\"$dev_host\""
            buildConfigField "String", "FILE_HOST", "\"$dev_file_host\""
            buildConfigField "String", "WORKSPACE_HOST", "\"$workspace_dev_host\""
            buildConfigField "String", "WORKSPACE_FILE_HOST", "\"$workspace_dev_file_host\""
            buildConfigField "String", "H5_HOST", "\"$h5_dev_host\""
        }
        prod {
            buildConfigField "String", "HOST", "\"$prod_host\""
            buildConfigField "String", "FILE_HOST", "\"$prod_file_host\""
            buildConfigField "String", "WORKSPACE_HOST", "\"$workspace_prod_host\""
            buildConfigField "String", "WORKSPACE_FILE_HOST", "\"$workspace_prod_file_host\""
            buildConfigField "String", "H5_HOST", "\"$h5_prod_host\""
        }
        train {
            buildConfigField "String", "HOST", "\"$train_host\""
            buildConfigField "String", "FILE_HOST", "\"$train_file_host\""
            buildConfigField "String", "WORKSPACE_HOST", "\"$workspace_train_host\""
            buildConfigField "String", "WORKSPACE_FILE_HOST", "\"$workspace_train_file_host\""
            buildConfigField "String", "H5_HOST", "\"$h5_train_host\""
        }
        sittest {
            buildConfigField "String", "HOST", "\"$test_host\""
            buildConfigField "String", "FILE_HOST", "\"$test_file_host\""
            buildConfigField "String", "WORKSPACE_HOST", "\"$workspace_test_host\""
            buildConfigField "String", "WORKSPACE_FILE_HOST", "\"$workspace_test_file_host\""
            buildConfigField "String", "H5_HOST", "\"$h5_test_host\""
        }
    }
    variantFilter { variant ->
        if (variant.buildType.name == 'release') {
            for (flavor in variant.flavors) {
                if (flavor.name != "prod") {
//                    variant.setIgnore(true)
                }
            }
        }
    }
    lintOptions {
        abortOnError false
        check 'Interoperability'
        checkReleaseBuilds false
        disable 'MissingTranslation'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}


dependencies {
    api project(':commonlib')
    kapt 'com.alibaba:arouter-compiler:1.1.4'
    if (!isModule.toBoolean()) {
        api project(':club_module')
        api project(':workspace_module')
    }
}

**Comment by ewgcat** [comment]
有没有测过tinker打包的情况

**Comment by ewgcat** [comment]
不用tinker打包支持，用tinker打包不支持

**Comment by 2BAB** [comment]
1. 你的 scripts 里没看到引入 scratch-paper
2. tinker 打包我没有测试过，但是 tinker 其实只有在你发 patch 的时候才真正会去 hook 打包的流程吧，本地打 debug 应该是没有影响？如果你不放心，可以先加个判断（debug 时不 apply tinker，还可以额外让编译快一点哈哈...），毕竟你的工程可能未来还会引入其他插件影响 resource 的编译

So, 总的来说是想问 Tinker 打包兼容的情况？（如果是的话我会改一下标题）

我今天稍晚会测试一下这块，谢谢。

**Comment by ewgcat** [comment]
好的

**Comment by 2BAB** [comment]
这边我测试的结果是使用了 apply plugin: 'com.tencent.tinker.patch' 和 apply plugin: 'tinkerpatch-support' 并进行相关配置之后，依旧可以正确使用。不知道能否提供详细的编译错误，或者是否有任何的其他提示？@ewgcat

**Comment by ewgcat** [comment]
apply from: 'tinker-support.gradle'不可以

**Comment by ewgcat** [comment]
项目地址：https://github.com/ewgcat/YiJianStaff

**Comment by ewgcat** [comment]
没有编译错误

**Comment by 2BAB** [comment]
@ewgcat I have found the issues, it's not about the thinker plugin, it's from the scratch-paper itself. 

Your project has multiple modules and you put the icons in the libraries, but **unfortunately scratch-paper didn't traverse all resources, it only finds icons from application module**. I will release a new build tomorrow tonight to fix it, and also give you an example of how to apply.

Here are some previews:

![ic_launcher](https://user-images.githubusercontent.com/5710495/46683880-e86a4380-cc23-11e8-90e1-c0cd80719181.png)
![screen shot 2018-10-10 at 00 27 18](https://user-images.githubusercontent.com/5710495/46683881-e86a4380-cc23-11e8-94f0-bc8261ac173c.png)

Thank you for your reply.

**Comment by 2BAB** [comment]
1. Because you are using an old tinker plugin, it seems that it will force using AAPT1, but scratch-paper now only supporting AAPT2, so please add this to your `build.gradle` 

```
debug {
            //混淆
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.releaseKey

            // add this line to enable aapt2, it will only impact debug building 
            project.setProperty("android.enableAapt2", "true") 
        }
```

( or update your tinker plugin to 1.9.9 to support AAPT2, check here https://github.com/Tencent/tinker/issues/811  and https://github.com/Tencent/tinker/releases/tag/v1.9.9 )


2. update to new scratch-paper 2.3.1

``` gradle
classpath 'me.2bab:scratch-paper:2.3.1'
...
apply plugin: 'me.2bab.scratchpaper'
scratchPaper {
    textSize = 13
    textColor = "#FFF"
    verticalLinePadding = 4
    backgroundColor = "#AA000000"
    extraInfo = new Date().format("MM-dd,HH:mm")

    // just remove these two lines so that scratch-paper will only work in debug mode
    // enableGenerateIconOverlay = true
    // enableGenerateBuildInfo = true

    // Experimental field
    // @see IconOverlayGenerator#removeXmlIconFiles
    enableXmlIconRemove = false
}
```

Cheers! 🍻 🍻 🍻 @ewgcat

**Comment by ewgcat** [comment]
可以了
