### ISSUE TITLE
支持apg 3.3

### ISSUE THREAD

**Issue by xckevin** [2BAB/ScratchPaper#5]
出现错误： NoClassDefFoundError: com/android/build/gradle/tasks/MergeManifests

**Comment by 2BAB** [comment]
Will try to support 3.3.x by this week. Pls follow up the update on this issue. Thanks!

**Comment by 2BAB** [comment]
Hi @xckevin , I have addressed the issue, you can try to update the plugin to `2.4.1` then it should be ok. Any other problems can open new issues, I will try to help ASAP. Thanks.

**Comment by xckevin** [comment]
@2BAB  good job!  Thanks a lot

**Comment by xckevin** [comment]
拾乂？   😂   交个朋友吧
